PerfumeProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('perfume_app.urls')),
    path('ai/', include('ai_app.urls')),
    path('',include('admin_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ai_app/urls.py
from django.urls import path

from . import views

app_name = 'ai_app'

urlpatterns = [
    path('question/', views.question, name='question'),
    path('result/',views.result,name='result'),
    path('confirm/', views.confirm, name='confirm'),
    path('order/', views.order, name='order'),

 ]

perfume_app/urls.py
from django.urls import path

from . import views

app_name = 'perfume_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_guide',views.user_guide,name='user_guide'),
    path('perfumes_list/',views.perfumes_list,name='perfumes_list'),
    path('perfume/<int:pk>',views.perfume_detail,name='perfume_detail'),
    path('perfume/<int:pk>/review',views.submit_review,name='submit_review'),

 ]

ai_app/models.py
from django.db import models
from admin_app.models import CustomUser
from perfume_app.models import Perfumes

# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    perfume = models.ForeignKey(Perfumes, on_delete=models.CASCADE)  # 新增這行
    perfume_name = models.CharField(max_length=100)
    perfume_brand = models.CharField(max_length=100)
    svg_value = models.CharField(max_length=50)
    name =  models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    post_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


ai_app/views.py
from django.contrib.auth.decorators import login_required
from .decorators import status_required, sample_order_check
from django.shortcuts import render,get_object_or_404
from perfume_app.models import Perfumes
from.models import Order
from admin_app.profiles import UserProfile

import requests
import ast
from dotenv import load_dotenv
import os

load_dotenv()
PERPLEXITY_API_KEY = os.getenv('PERPLEXITY_API_KEY')

# Create your views here.
@login_required
def question(request):
    return render(request,'ai_app/question.html')

def query_perplexity_api(questions):
    url = "https://api.perplexity.ai/chat/completions"
    headers = {
        "Authorization": f"Bearer {PERPLEXITY_API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": "sonar-pro",
        "messages": [
            {"role": "user", "content": questions},
        ]
    }
    response = requests.post(url, json=payload, headers=headers)
    print("Status code:", response.status_code)
    print("Response content:", response.text)
    if response.status_code == 200:
        return response.json()["choices"][0]["message"]["content"]
    else:
        return f"Error: {response.status_code} - {response.text}"

@login_required
def result(request):

    if request.method == "POST":
        gender = request.POST.get('gender')
        time_choices = request.POST.getlist('time[]')
        seasons = request.POST.getlist('season[]')
        longevity = request.POST.get('longevity')
        sillage = request.POST.get('sillage')

        create_question = f'請在fragrantica.com及各大香水網站去尋找以下牌子裹(不分次序):Chanel,Christian Dior,Creed,Diptyque,Frederic Malle,Hermes,Jo Malone,Le Labo,Maison Martin Margiela,Parfums de Marly,Tom Ford,Yves Saint Laurent而且適合以下條件的香水: {gender},{",".join(time_choices)},{",".join(seasons)},{longevity},{sillage},請選出4款評價好的香水,請將香水名子(牌子名不要)放入selected_names = [ ], 其他文字都不要'

        api_response = query_perplexity_api(create_question)

        try:
            selected_names = ast.literal_eval(api_response.split('=')[1].strip())  # 轉成Python list
        except Exception:
            selected_names = []


        p = Perfumes.objects.filter(name__in=selected_names)

        context = {
            'perfumes': p,
            'api_response':api_response,
            'create_question':create_question,
        }
        return render(request, 'ai_app/result.html', context)

@status_required
@sample_order_check
def confirm(request):

    perfume_id = request.GET.get('perfume_id')

    perfume = get_object_or_404(Perfumes, pk=perfume_id)

    try:
        user = request.user
        profile = UserProfile.objects.get(user_id=user.id)
        address = profile.address
        name = profile.name
    except UserProfile.DoesNotExist:
        address = 'Unknow'
        name = 'Unknow'

    context = {
        'perfume': perfume,
        'address': address,
        'name': name,

    }
    return render(request, 'ai_app/confirm.html', context)

@status_required
def order(request):
    perfume_id = request.GET.get('perfume_id')

    perfume = get_object_or_404(Perfumes, pk=perfume_id)

    if request.method == "POST":
        perfume_name = request.POST.get("perfume_name")
        perfume_brand = request.POST.get("perfume_brand")
        svg_value = request.POST.get("svg_value")
        name = request.POST.get("name")
        address = request.POST.get("address")

        # 建立訂單
        Order.objects.create(
            user=request.user,
            perfume = perfume,
            perfume_name=perfume_name,
            perfume_brand=perfume_brand,
            svg_value=svg_value,
            name = name,
            address=address,
        )

        # 更新資料
        profile = UserProfile.objects.get(user_id=request.user.id)
        if profile:
            profile.name = name
            profile.address = address
            profile.status = False
            profile.save()
        else:
            # 如果不存在可建立
            UserProfile(user_id=request.user.id, name=name, address=address,point=0,status=False).save()


        return render(request, "ai_app/order.html")


ai_app/templates/ai_app/confirm.html
{% extends "base.html" %}
{% load static %}
{% block head_style %}
<link rel="stylesheet" href="{% static 'ai_app/css/confirm.css'%}">
{% endblock %}
{% block title %}Confirm Sample Order{% endblock %}
{% block body_content %}
  <form method="post" action="{% url 'ai_app:order' %}?perfume_id={{ perfume.pk }}">
  {% csrf_token %}
    <div class="row align-items-start">
      <div class="col-md-6 perfume-image mb-4 mb-md-0">
        <img src="{% static 'ai_app/images/sample.jpeg'%}" alt="Sample" width="350px" class="img-fluid rounded shadow-sm">
      </div>

      <div class="col-md-6 perfume-details">
        <h5 class="text-secondary fw-semibold" >{{ perfume.brand }}</h5>
        <input type="hidden" name="perfume_brand" value="{{ perfume.brand }}">
        <h2 class="fw-bold mb-4" >{{ perfume.name }}</h2>
        <input type="hidden" name="perfume_name" value="{{ perfume.name }}">
        <p>Choose one to your special package</p>
        <div class="svg-options">
           <svg data-value="diamond" class="svg-option" xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="grey" viewBox="0 0 16 16" >
            <path d="M2.45 7.4 7.2 1.067a1 1 0 0 1 1.6 0L13.55 7.4a1 1 0 0 1 0 1.2L8.8 14.933a1 1 0 0 1-1.6 0L2.45 8.6a1 1 0 0 1 0-1.2"/>
          </svg>
          <svg data-value="club" class="svg-option" xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="grey" viewBox="0 0 16 16">
            <path d="M11.5 12.5a3.5 3.5 0 0 1-2.684-1.254 20 20 0 0 0 1.582 2.907c.231.35-.02.847-.438.847H6.04c-.419 0-.67-.497-.438-.847a20 20 0 0 0 1.582-2.907 3.5 3.5 0 1 1-2.538-5.743 3.5 3.5 0 1 1 6.708 0A3.5 3.5 0 1 1 11.5 12.5"/>
          </svg>
          <svg data-value="heart" class="svg-option" xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="grey" viewBox="0 0 16 16">
            <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1"/>
          </svg>
          <svg data-value="spade" class="svg-option" xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="grey" viewBox="0 0 16 16">
            <path d="M7.184 11.246A3.5 3.5 0 0 1 1 9c0-1.602 1.14-2.633 2.66-4.008C4.986 3.792 6.602 2.33 8 0c1.398 2.33 3.014 3.792 4.34 4.992C13.86 6.367 15 7.398 15 9a3.5 3.5 0 0 1-6.184 2.246 20 20 0 0 0 1.582 2.907c.231.35-.02.847-.438.847H6.04c-.419 0-.67-.497-.438-.847a20 20 0 0 0 1.582-2.907"/>
          </svg>
          <input type="hidden" name="svg_value" id="svgValueInput" value="">
        </div>

          <label for ="name">Your Name</label><br>
          <input type="text" name = "name" id="name" value="{{name}}" class="form-control">
          <label for ="address">Your Delivery Address</label><br>
          <input type="text" name = "address" id="address" value="{{address}}" class="form-control">

          <button type="submit" id="submit-btn" class="btn btn-info btn-lg">Confirm</button>
      </div>
    </div>
  </form>
{%  endblock %}
{% block body_script %}
<script src="{% static 'ai_app/js/confirm.js'%}"></script>
{% endblock %}

ai_app/templates/ai_app/order.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'ai_app/css/order.css'%}">
    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/png" />
    <title>Scent φ - Sample Order successfully</title>
</head>
<body>
    <div class="center-container">
        <h1>Sample Order successfully</h1>
        <img src="{% static 'ai_app/images/present.png'%}" alt="open_present" width="500px">
        <h2>We will send the sample to you within 2-3 working days</h2>
        <!-- 倒數提示 -->
        <h3 id="countdown-text" data-url="{% url 'perfume_app:index' %}">Redirecting to Homepage in <span id="countdown-number">5</span> seconds...</h3>
    </div>
    <script src="{% static 'ai_app/js/order.js'%}"></script>
</body>
</html>

ai_app/templates/ai_app/question.html
{% extends "base.html" %}
{% load static %}
{% block head_style %}
<link rel="stylesheet" href="{% static 'ai_app/css/question.css'%}">
{% endblock %}
{% block title %}Questions to AI{% endblock %}
{% block body_content %}
    <form class="form" action="{% url 'ai_app:result' %}" method="POST">
        {% csrf_token %}
        <div class="form-header">
        <h2>Question</h2>
        <div>
            <p>Which gender do you identify as?</p>
            <label for="gender1">
            <input type="radio" name="gender" id="gender1" value="Female">Female
            </label>
            <label for="gender2">
            <input type="radio" name="gender" id="gender2" value="Male">Male
            </label>
            <label for="gender3">
            <input type="radio" name="gender" id="gender3" value="Unisex" >Unisex
            </label>
        </div>
        <div>
            <p>When do you like to wear fragrance? (You can choose more than one)</p>
            <label for ="time1">
                <input type="checkbox" name="time[]" id="time1" value="Daytime">Daytime
            </label>
            <label for ="time2">
                <input type="checkbox" name="time[]" id="time2" value="Evening">Evening
            </label>

        </div>
        <div>
            <p>Which season(s) do you prefer to wear ? (You can choose more than one)</p>
            <label for ="season1">
                <input type="checkbox" name="season[]" id="season1" value="Spring">Spring
            </label>
            <label for ="season2">
                <input type="checkbox" name="season[]" id="season2" value="Summer">Summer
            </label>
            <label for ="season3">
                <input type="checkbox" name="season[]" id="season3" value="Autumn">Autumn
            </label>
            <label for ="season4">
                <input type="checkbox" name="season[]" id="season4" value="Winter">Winter
            </label>

        </div>
        <div>
            <p>Longevity</p>
            <label for="longevity1">
            <input type="radio" name="longevity" id="longevity1" value="longevity:very weak">very weak
            </label>
            <label for="longevity2">
            <input type="radio" name="longevity" id="longevity2" value="longevity:weak">weak
            </label>
            <label for="longevity3">
            <input type="radio" name="longevity" id="longevity3" value="longevity:moderate" >moderate
            </label>
            <label for="longevity4">
            <input type="radio" name="longevity" id="longevity4" value="longevity:long lasting" >long lasting
            </label>
            <label for="longevity5">
            <input type="radio" name="longevity" id="longevity5" value="longevity:eternal" >eternal
            </label>
        </div>
        <div>
            <p>Sillage</p>
            <label for="sillage1">
            <input type="radio" name="sillage" id="sillage1" value="sillage:intimate">intimate
            </label>
            <label for="sillage2">
            <input type="radio" name="sillage" id="sillage2" value="sillage:moderate">moderate
            </label>
            <label for="sillage3">
            <input type="radio" name="sillage" id="sillage3" value="sillage:strong" >strong
            </label>
            <label for="sillage4">
            <input type="radio" name="sillage" id="sillage4" value="sillage:enormous" >enormous
            </label>
        </div>


        <div>
            <button type="submit" id="submit">Recommend Perfumes</button>
        </div>
        </div>
    </form>

{%  endblock %}

ai_app/templates/ai_app/result.html
{% extends "base.html" %}
{% load static %}
{% block head_style %}
<link rel="stylesheet" href="{% static 'ai_app/css/result.css'%}">
{% endblock %}
{% block title %}Results by AI{% endblock %}
{% block body_content %}
   <div class="row row-cols-1 row-cols-md-4 g-4">
  {% for p in perfumes %}
  <div class="col item">
    <div class="card">
      <a href="{% url 'perfume_app:perfume_detail' p.pk %}">
        <img src="https://fimgs.net/mdimg/perfume-thumbs/375x500{{ p.image }}" class="card-img-top img-fluid" alt="{{ p.name }}">
      </a>
      <div class="card-body">
        <h5 class="card-title"><a href="{% url 'perfume_app:perfume_detail' p.pk %}">{{ p.brand }}</a></h5>
        <p class="card-text"><a href="{% url 'perfume_app:perfume_detail' p.pk %}">{{ p.name }}</a></p>
        <a href="{% url 'ai_app:confirm' %}?perfume_id={{ p.pk }}" class="btn btn-primary btn-sm get-sample-btn">Get sample</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{%  endblock %}
{% block body_script %}
  <script src="{% static 'ai_app/js/result.js'%}"></script>
{% endblock %}