PerfumeProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('perfume_app.urls')),
    path('ai/', include('ai_app.urls')),
    path('',include('admin_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_app/urls.py
from django.urls import path

from . import views

app_name = 'admin_app'

urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('profile/',views.profile,name='profile'),
    path('account/delete/', views.delete_account, name='delete_account'),

 ]

ai_app/urls.py
from django.urls import path

from . import views

app_name = 'ai_app'

urlpatterns = [
    path('question/', views.question, name='question'),
    path('result/',views.result,name='result'),
    path('confirm/', views.confirm, name='confirm'),
    path('order/', views.order, name='order'),

 ]

perfume_app/urls.py
from django.urls import path

from . import views

app_name = 'perfume_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_guide',views.user_guide,name='user_guide'),
    path('perfumes_list/',views.perfumes_list,name='perfumes_list'),
    path('perfume/<int:pk>',views.perfume_detail,name='perfume_detail'),
    path('perfume/<int:pk>/review',views.submit_review,name='submit_review'),

 ]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/png" />
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
    {% block head_style %}
    {% endblock %}

    <title>Scent φ - {% block title %}{% endblock %}</title>
</head>
<body>

     <header>
         <!-- logo -->
        <div id="logo">
            <img src="{% static 'images/logo.png' %}" alt="logo" width="70">
        </div>
         <!-- 左側色彩面板 -->
        <div id="colorPanel">
          <h4>Change Color</h4>
          <div id="colorButtons">
            <button class="color-btn" style="background-color: #ec6d71;"></button>
            <button class="color-btn" style="background-color: #f4b3c2;"></button>
            <button class="color-btn" style="background-color: #bce2e8;"></button>
            <button class="color-btn" style="background-color: #a6c8b2;"></button>
            <button class="color-btn" style="background-color: #a59aca;"></button>
            <button class="color-btn" style="background-color: #f8e58c;"></button>
            <button class="default-btn" style="background-color: #ece2ccad;">Default</button>
          </div>
        </div>
      <form method="get" action="{% url 'perfume_app:perfumes_list' %}" id="searchForm1">
          <input type="search" name="q" class="search-input" placeholder="Search for brand,name and notes" autocomplete="off" />
      </form>
        <nav>
          <ul class="nav-menu">
            <li>
                <a href="{% url 'perfume_app:index'%}">
                    <i class="nav-icon fas fa-home"></i> Home
                </a>
            </li>
            <li>
                <a href="{% url 'perfume_app:perfumes_list'%}">
                    <i class="fa-solid fa-spray-can-sparkles"></i> Perfume
                </a>
            </li>
            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'ai_app:question'%}">
                <i class="bi bi-perplexity"></i>AI
              </a>
            </li>
            {% endif %}
            {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin:login' %}">
                    <i class="fa-solid fa-gear"></i> Admin Settings
                </a>
            </li>
            {% endif %}
            <li>
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle d-flex align-items-center"
                       role="button" data-bs-toggle="dropdown">
                            <img src="{{ user.avatar.url }}"
                             alt="{{ user.username }}"
                             class="rounded-circle me-2"
                             style="width: 50px; height: 50px; object-fit: cover;">

                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu">
                        {% if not request.user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'admin_app:profile'%}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                        <li><a class="dropdown-item" href="{% url 'admin_app:delete_account' %}">Delete account</a></li>
                        {% endif %}

                        <li>
                            <a href="#" class="dropdown-item btn-logout">Logout</a>
                            <form id="logoutForm" action="{% url 'logout' %}" method="post" style="display:none;">
                                {% csrf_token %}
                            </form>
                        </li>
                    </ul>
                </div>
            </li>
            {% else %}
               <li>
                   <div class="dropdown">
                       <a href="#" class="nav-link dropdown-toggle d-flex align-items-center" role="button" data-bs-toggle="dropdown" style="color:#007bff;">
                           <i class="fa-regular fa-user"></i> Member
                       </a>
                       <ul class="dropdown-menu">
                           <li><a href="{% url 'admin_app:signup' %}" class="dropdown-item">Signup</a></li>
                           <li><a href="{% url 'login' %}" class="dropdown-item">Login</a></li>
                        </ul>
                   </div>
               </li>
            {% endif %}
              <li>
                <a href="{% url 'perfume_app:user_guide'%}">
                    <img src="{% static 'images/icon1.png' %}" alt="logo" width="50">
                </a>
              </li>
          </ul>
        </nav>
    </header>
        <main class="wallpaper-container">
            <div class="content">
            {% block body_content %}
            {% endblock %}
            </div>
            <div class="scroll-top">
               <p><a href="#"><img src="{% static 'images/top_button.png' %}" alt="Scroll Top" width="50" height="50"></a></p>
            </div>
        </main>

    <footer>
      <div class="sns-icons">
        <a href="#"><img src="{% static 'images/twitter.png' %}" alt="twitter" width="32"></a>
        <a href="#"><img src="{% static 'images/facebook.png' %}" alt="facebook" width="32"></a>
        <a href="#"><img src="{% static 'images/instagram.png' %}" alt="instagram" width="32"></a>
      </div>
      <p><small>Copyright &copy; 2025 Messager of scent Ltd. All Rights Reserved.</small></p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
     {% if messages %}
      <script>
        {% for message in messages %}
          Swal.fire({
            icon: 'info',
            text: "{{ message }}",
          });
        {% endfor %}
      </script>
    {% endif %}
    <script src="{% static 'js/base.js'%}"></script>
     {% block body_script %}
     {% endblock %}
</body>
</html>